import { IpeopleImages } from '../../type/interfaces';
export const peopleImages: IpeopleImages = {
  'no Icon': '/assets/People/Page1/noIcon.webp',
  'Luke Skywalker': '/assets/People/Page1/Luke_Skywalker.webp',
  'C-3PO': '/assets/People/Page1/C-3PO.webp',
  'R2-D2': '/assets/People/Page1/R2-D2.webp',
  'Darth Vader': '/assets/People/Page1/Darth_Vader.webp',
  'Leia Organa': '/assets/People/Page1/Leia_Organa.webp',
  'Owen Lars': '/assets/People/Page1/Owen_Lars.webp',
  'Beru Whitesun lars': '/assets/People/Page1/Beru_Whitesun_lars.webp',
  'R5-D4': '/assets/People/Page1/R5-D4.webp',
  'Biggs Darklighter': '/assets/People/Page1/Biggs_Darklighter.webp',
  'Obi-Wan Kenobi': '/assets/People/Page1/Obi-Wan_Kenobi.webp',
  'Anakin Skywalker': '/assets/People/Page2/Anakin_Skywalker.webp',
  'Wilhuff Tarkin': '/assets/People/Page2/Wilhuff_Tarkin.webp',
  Chewbacca: '/assets/People/Page2/Chewbacca.webp',
  'Han Solo': '/assets/People/Page2/Han_Solo.webp',
  Greedo: '/assets/People/Page2/Greedo.webp',
  'Jabba Desilijic Tiure': '/assets/People/Page2/Jabba_Desilijic_Tiure.webp',
  'Wedge Antilles': '/assets/People/Page2/Wedge_Antilles.webp',
  'Jek Tono Porkins': '/assets/People/Page2/Jek_Tono_Porkins.webp',
  Yoda: '/assets/People/Page2/Yoda.webp',
  Palpatine: '/assets/People/Page2/Palpatine.webp',
  'Boba Fett': '/assets/People/Page3/Boba_Fett.webp',
  'IG-88': '/assets/People/Page3/IG-88.webp',
  Bossk: '/assets/People/Page3/Bossk.webp',
  'Lando Calrissian': '/assets/People/Page3/Lando_Calrissian.webp',
  Lobot: '/assets/People/Page3/Lobot.webp',
  Ackbar: '/assets/People/Page3/Ackbar.webp',
  'Mon Mothma': '/assets/People/Page3/Mon_Mothma.webp',
  'Arvel Crynyd': '/assets/People/Page3/Arvel_Crynyd.webp',
  'Wicket Systri Warrick': '/assets/People/Page3/Wicket_Systri_Warrick.webp',
  'Nien Nunb': '/assets/People/Page3/Nien_Nunb.webp',
  'Qui-Gon Jinn': '/assets/People/Page4/Qui-Gon_Jinn.webp',
  'Nute Gunray': '/assets/People/Page4/Nute_Gunray.webp',
  'Finis Valorum': '/assets/People/Page4/Finis_Valorum.webp',
  'Padmé Amidala': '/assets/People/Page4/Padmé_Amidala.webp',
  'Jar Jar Binks': '/assets/People/Page4/Jar_Jar_Binks.webp',
  'Roos Tarpals': '/assets/People/Page4/Roos_Tarpals.webp',
  'Rugor Nass': '/assets/People/Page4/Rugor_Nass.webp',
  'Ric Olié': '/assets/People/Page4/Ric_Olié.webp',
  Watto: '/assets/People/Page4/Watto.webp',
  Sebulba: '/assets/People/Page4/Sebulba.webp',
};
